/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LogEventListener */

#ifndef _Included_LogEventListener
#define _Included_LogEventListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LogEventListener
 * Method:    listenToEvents
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LogEventListener_listenToEvents
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
