/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ReadingLogName */

#ifndef _Included_ReadingLogName
#define _Included_ReadingLogName
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ReadingLogName
 * Method:    readLogEvents
 * Signature: (Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_ReadingLogName_readLogEvents
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
