/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WmiClientClassJson */

#ifndef _Included_WmiClientClassJson
#define _Included_WmiClientClassJson
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WmiClientClassJson
 * Method:    createConnection
 * Signature: (Ljava/lang/String;Ljava/util/HashMap;Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_WmiClientClassJson_createConnection
  (JNIEnv *, jobject, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
